---
title: "Bantu Migration Analyses"
author: "Colby Ford"
date: "February 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dataload}
## Load in YChr, mtDNA, and Cultural data
## Load in tree files
library(ape)
library(Biostrings)
ychrdata <- read.nexus("C:/Users/Colby Ford/Dropbox/ChrY.Bantu542/ChrY.Bantu542.10062017simple.consensus.nex")
mtdnadata <- readDNAStringSet("C:/Users/Colby Ford/Dropbox/mt_over_Bantu542/with-outgroups/mafft/mt_over_Bantu542_newID.mafft.dantrim.out.fasta")
culturaldata <- read.nexus("C:/Users/Colby Ford/Dropbox/BantuBantoid_Culture/colby-run/BantuBantoid_Culture_MX.nexus")

combinedpoyoutput <- read.nexus("C:/Users/Colby Ford/Dropbox/Bantu_CombinedData_dan/forthtry/my_100repEfi_trees_GuthrieZones.root800jaghams4try.nex")

```


```{r mcsim}
## Monte Carlo Simulation
```

```{r seqanalysis}
## Sequence Alignment Comparison
#install.packages("AlignStat")
library(AlignStat)

comp <- compare_alignments(ref, com, SP = TRUE, CS = TRUE)
```

```{r mds}
## Nonmetric MDS
# N rows (objects) x p columns (variables)
# each row identified by a unique row name

library(MASS)
d <- dist(mydata) # euclidean distances between the rows
fit <- isoMDS(d, k=2) # k is the number of dim
fit # view results

# plot solution
x <- fit$points[,1]
y <- fit$points[,2]
plot(x, y, xlab="Coordinate 1", ylab="Coordinate 2",
  main="Nonmetric MDS", type="n")
text(x, y, labels = row.names(mydata), cex=.7) 
```

```{r le}
## Laplacian Eigenmaps
#install.packages("dimRed")
```